Block/Form/Type/MenuType.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Zikula package.
 *
 * Copyright Zikula - https://ziku.la/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Zikula\MenuModule\Block\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Exception\TransformationFailedException;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Contracts\Translation\TranslatorInterface;
use Translation\Extractor\Annotation\Translate;
use Zikula\Bundle\CoreBundle\Translation\TranslatorTrait;

class MenuType extends AbstractType
{
    use TranslatorTrait;

    public function __construct(TranslatorInterface $translator)
    {
        $this->setTranslator($translator);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Menu name',
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('options', TextType::class, [
                'required' => false,
                'invalid_message' => 'Could not json_decode the string you entered.',
                'alert' => [/** @Translate */ 'This must be a json_encoded string of option key-value pairs.' => 'warning']
            ])
        ;
        $builder->get('options')
            ->addModelTransformer(new CallbackTransformer(
                static function ($text) {
                    return $text;
                },
                static function ($text) {
                    if (empty($text)) {
                        return '{}';
                    }
                    $json = str_replace("'", '"', $text);
                    if (null === json_decode($json, true)) {
                        throw new TransformationFailedException($this->trans('Could not json_decode the string you entered.'));
                    }

                    return $json;
                }
            ))
        ;
    }

    public function getBlockPrefix()
    {
        return 'zikulamenumodule_menu';
    }
}

Form/Type/HiddenMenuItemType.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Zikula package.
 *
 * Copyright Zikula - https://ziku.la/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Zikula\MenuModule\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;
use Zikula\Bundle\CoreBundle\Translation\TranslatorTrait;
use Zikula\MenuModule\Entity\RepositoryInterface\MenuItemRepositoryInterface;
use Zikula\MenuModule\Form\DataTransformer\MenuItemEntityTransformer;

class HiddenMenuItemType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var MenuItemRepositoryInterface
     */
    private $repository;

    public function __construct(
        TranslatorInterface $translator,
        MenuItemRepositoryInterface $repository
    ) {
        $this->setTranslator($translator);
        $this->repository = $repository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $transformer = new MenuItemEntityTransformer($this->repository, $this->translator);
        $builder->addViewTransformer($transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'invalid_message' => 'The selected item does not exist'
        ]);
    }

    public function getParent()
    {
        return HiddenType::class;
    }
}

Controller/MenuController.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Zikula package.
 *
 * Copyright Zikula - https://ziku.la/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Zikula\MenuModule\Controller;

use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Zikula\Bundle\CoreBundle\Controller\AbstractController;
use Zikula\MenuModule\Entity\MenuItemEntity;
use Zikula\MenuModule\Entity\Repository\MenuItemRepository;
use Zikula\MenuModule\Form\Type\DeleteMenuItemType;
use Zikula\MenuModule\Form\Type\MenuItemType;
use Zikula\PermissionsModule\Annotation\PermissionCheck;
use Zikula\ThemeModule\Engine\Annotation\Theme;

/**
 * Class MenuController
 *
 * @Route("/admin")
 * @PermissionCheck("admin")
 */
class MenuController extends AbstractController
{
    /**
     * @var string
     */
    private $domTreeNodePrefix = 'node_';

    /**
     * @Route("/list")
     * @Template("@ZikulaMenuModule/Menu/list.html.twig")
     * @Theme("admin")
     */
    public function listMenus(
        MenuItemRepository $menuItemRepository
    ): array {
        return [
            'rootNodes' => $menuItemRepository->getRootNodes()
        ];
    }

    /**
     * @Route("/view/{id}")
     * @Template("@ZikulaMenuModule/Menu/view.html.twig")
     * @Theme("admin")
     *
     * @see https://jstree.com/
     * @see https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/tree.md
     * @throws AccessDeniedException Thrown if the menu item is not a root item
     */
    public function view(
        MenuItemRepository $menuItemRepository,
        MenuItemEntity $menuItemEntity
    ): array {
        if (null !== $menuItemEntity->getParent()) {
            throw new AccessDeniedException();
        }
        $htmlTree = $menuItemRepository->childrenHierarchy(
            $menuItemEntity, /* node to start from */
            false, /* false: load all children, true: only direct */
            [
                'decorate' => true,
                'html' => true,
                'childOpen' => function ($node) {
                    return '<li class="jstree-open" id="' . $this->domTreeNodePrefix . $node['id'] . '">';
                },
                'nodeDecorator' => static function ($node) {
                    return '<a href="#">' . $node['title'] . ' (' . $node['id'] . ')</a>';
                }
            ]
        );

        return [
            'menu' => $menuItemEntity,
            'tree' => $htmlTree
        ];
    }

    /**
     * @Route("/edit/{id}", defaults={"id" = null})
     * @Theme("admin")
     */
    public function edit(
        Request $request,
        ManagerRegistry $doctrine,
        MenuItemRepository $menuItemRepository,
        MenuItemEntity $menuItemEntity = null
    ): Response {
        if (!isset($menuItemEntity)) {
            $menuItemEntity = new MenuItemEntity();
        }
        $form = $this->createForm(MenuItemType::class, $menuItemEntity);
        $form->add('save', SubmitType::class, [
            'label' => $this->trans('Save'),
            'icon' => 'fa-check',
            'attr' => [
                'class' => 'btn btn-success'
            ]
        ])
        ->add('cancel', SubmitType::class, [
            'label' => $this->trans('Cancel'),
            'icon' => 'fa-times',
            'attr' => [
                'class' => 'btn btn-secondary'
            ]
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid() && $form->get('save')->isClicked()) {
            $menuItemEntity = $form->getData();
            $menuItemRepository->persistAsFirstChild($menuItemEntity);
            if (null === $menuItemEntity->getId()) {
                // create dummy child
                $dummy = new MenuItemEntity();
                $dummy->setTitle('dummy child');
                $menuItemRepository->persistAsFirstChildOf($dummy, $menuItemEntity);
            }
            $doctrine->getManager()->flush();

            return $this->redirectToRoute('zikulamenumodule_menu_list');
        }
        if ($form->isSubmitted() && $form->get('cancel')->isClicked()) {
            $this->addFlash('status', 'Operation cancelled.');

            return $this->redirectToRoute('zikulamenumodule_menu_list');
        }

        return $this->render('@ZikulaMenuModule/Menu/editRootNode.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/delete/{id}")
     * @Template("@ZikulaMenuModule/Menu/delete.html.twig")
     * @Theme("admin")
     *
     * @return array|RedirectResponse
     */
    public function delete(Request $request, ManagerRegistry $doctrine, MenuItemEntity $menuItemEntity)
    {
        $form = $this->createForm(DeleteMenuItemType::class, [
            'entity' => $menuItemEntity
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isSubmitted() && $form->get('delete')->isClicked()) {
                $menuItemEntity = $form->get('entity')->getData();
                $doctrine->getManager()->remove($menuItemEntity);
                $doctrine->getManager()->flush();
                $this->addFlash('status', 'Done! Menu removed.');
            } elseif ($form->isSubmitted() && $form->get('cancel')->isClicked()) {
                $this->addFlash('status', 'Operation cancelled.');
            }

            return $this->redirectToRoute('zikulamenumodule_menu_list');
        }

        return [
            'form' => $form->createView()
        ];
    }
}

Resources/views/Menu/delete.html.twig
{{ pageSetVar('title', 'Delete Root'|trans) }}
<h3>
    <span class="fas fa-trash-alt"> {% trans %}Delete Root{% endtrans %}</span>
</h3>
<div class="alert alert-danger">{% trans with {'%menu%': form.vars.value.entity.title} %}Are you sure you want to delete this menu (%menu%) AND ALL ITS CHILDREN?{% endtrans %}</div>
{{ form_start(form) }}
{{ form_errors(form) }}
<div class="form-group row">
    <div class="col-md-9 offset-md-3">
        {{ form_widget(form.delete) }}
        {{ form_widget(form.cancel) }}
    </div>
</div>
{{ form_end(form) }}

Resources/views/Menu/edit.html.twig
<div id="form_container">
    {{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_row(form.title) }}
    <div class="form-group row">
        {{ form_label(form.options) }}
        <div class="col-md-9">
            <ul class="list-unstyled" id="options" data-prototype="&lt;li class=&quot;form-inline&quot;&gt;{{ form_widget(form.options.vars.prototype.key)|e }} {{ form_widget(form.options.vars.prototype.value)|e }}&nbsp;&nbsp;&lt;a href=&quot;#&quot; class=&quot;delete-option fas fa-trash-alt fa-lg text-danger&quot;&gt;&lt;/a&gt;&lt;/li&gt;">
                {% for keyValuePair in form.options %}
                    {% form_theme form _self %}
                    {% block _options_entry_widget %}
                        <li class="form-inline">{{ form_widget(keyValuePair.key) }} {{ form_widget(keyValuePair.value) }}&nbsp;&nbsp;<a href="#" class="delete-option fas fa-trash-alt fa-lg text-danger"></a></li>
                    {% endblock %}
                {% endfor %}
            </ul>
            <div class="alert alert-info">{% trans %}Options with an asterisk (*) must have a value of a json_encoded string of option key-value pairs. Options with a plus (+) must have a boolean value.{% endtrans %}</div>
            <a href="#" id="add-option" class="btn btn-secondary btn-sm fas fa-plus"> {% trans %}Add Option{% endtrans %}</a>
        </div>
    </div>
    {{ form_row(form.root) }}
    {{ form_row(form.parent) }}
    <div class="form-group row">
        <div class="col-md-9 offset-md-3">
            {% if form.save|default %}{{ form_widget(form.save) }}{% endif %}
            {% if form.cancel|default %}{{ form_widget(form.cancel) }}{% endif %}
            {{ form_end(form) }}
        </div>
    </div>
</div>
<div id="optionDefinitions" data-count="{{ form.options|length }}"></div>

Resources/views/Menu/editRootNode.html.twig
{{ pageSetVar('title', 'Create or Edit Root Node'|trans) }}
<h3>
    <span class="fas fa-plus"> {% trans %}Create or edit root node{% endtrans %}</span>
</h3>
{{ include('@ZikulaMenuModule/Menu/edit.html.twig') }}
{{ pageAddAsset('javascript', zasset('@ZikulaMenuModule:js/Zikula.Menu.Node.Edit.js')) }}

Resources/views/Menu/list.html.twig
{{ pageSetVar('title', 'Menu list'|trans) }}
<h3><span class="fas fa-list"></span> {% trans %}Menus{% endtrans %}</h3>
<table id="menu-list" class="table table-bordered table-striped">
    <colgroup>
        <col id="cMenuId" />
        <col id="cMenuTitle" />
        <col id="cMenuChildCount" />
        <col id="cMenuActions" />
    </colgroup>
    <thead>
        <tr>
            <th id="hMenuId" scope="col">{% trans %}ID{% endtrans %}</th>
            <th id="hMenuTitle" scope="col">{% trans %}Title{% endtrans %}</th>
            <th id="hMenuChildCount" scope="col">{% trans %}Children{% endtrans %}</th>
            <th id="hMenuActions" scope="col" class="text-right">{% trans %}Actions{% endtrans %}</th>
        </tr>
    </thead>
    <tbody>
        {% for node in rootNodes %}
        <tr>
            <td headers="hMenuId">{{ node.id }}</td>
            <td headers="hMenuTitle"><strong>{{ node.title }}</strong></td>
            <td headers="hMenuChildCount">
                {{ 'plural_n.direct.child'|trans({count: node.children.count})|desc('{count, plural,\n  one   {one direct child}\n  other {# direct children}\n}') }}
            </td>
            <td headers="hMenuActions" class="actions">
                {% set rowActions = knp_menu_get('zikulaMenuAdminActionsMenu', [], {id: node.id}) %}
                {{ knp_menu_render(rowActions, {template: '@ZikulaMenuModule/Override/actions.html.twig'}) }}
            </td>
        </tr>
        {% else %}
        <tr class="table-info"><td colspan="4" class="text-center">{% trans %}No items found.{% endtrans %}</td></tr>
        {% endfor %}
    </tbody>
</table>

Resources/views/Menu/view.html.twig
{{ pageSetVar('title', 'Menu'|trans) }}
<h3>
    <span class="fas fa-list"></span>
    {% trans %}Menu{% endtrans %}
</h3>
<div class="alert alert-info">{% trans %}Right-click on the menu-item for a context menu of actions.{% endtrans %}</div>
<h4><i class="fas fa-bars"></i> {{ menu.title }} ({{ menu.id }})</h4>
<div class="alert alert-info"><i class="fas fa-check-circle"></i> {% trans %}MenuItemName (menuItemId). The id is needed for permissions.{% endtrans %}</div>
<div id="tree_container">
    {{ tree|raw }}
</div>
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">{% trans %}Edit item{% endtrans %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="{% trans %}Close{% endtrans %}"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" value="Submit" class="btn btn btn-success"><i class="fas fa-check"></i> {% trans %}Save{% endtrans %}</button>
                <button type="button" value="Cancel" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times"></i> {% trans %}Cancel{% endtrans %}</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">{% trans %}Confirmation prompt{% endtrans %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="{% trans %}Close{% endtrans %}"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p>{% trans %}Do you really want to delete this item?{% endtrans %}
                <p id="deleteWithChildrenInfo"></p>
            </div>
            <div class="modal-footer">
                <button type="button" id="node_delete" value="Delete" class="btn btn-danger"><i class="fas fa-trash-alt"></i> {% trans %}Delete{% endtrans %}</button>
                <button type="button" id="node_delete_all" value="Delete" class="btn btn-danger d-none"><i class="fas fa-trash-alt"></i> {% trans %}Delete all children{% endtrans %}</button>
                <button type="button" id="node_delete_move" value="DeleteAndMoveChildren" class="btn btn-danger d-none">{% trans %}Move all children{% endtrans %}</button>
                <button type="button" id="node_delete_move_action" value="DeleteAndMoveChildren" class="btn btn-danger d-none">{% trans %}Move and delete{% endtrans %}</button>
                <button type="button" id="node_cancel" value="Cancel" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times"></i> {% trans %}Cancel{% endtrans %}</button>
            </div>
        </div>
    </div>
</div>
{{ pageAddAsset('javascript', asset('jstree/dist/jstree.min.js')) }}
{{ pageAddAsset('stylesheet', asset('jstree/dist/themes/default/style.min.css')) }}
{{ pageAddAsset('stylesheet', zasset('@ZikulaThemeModule:css/jstree.Common.css')) }}
{{ pageAddAsset('javascript', zasset('@ZikulaMenuModule:js/ZikulaMenuModule.Admin.View.js')) }}
{{ pageAddAsset('javascript', zasset('@ZikulaMenuModule:js/Zikula.Menu.Node.Edit.js')) }}